### ISSUE TITLE
Which version of emscripten is this compiled with?

### ISSUE THREAD

**Issue by cuardin** [tonyg/js-scrypt#13]
Hi.
When I download the code and run it in my browser, it works perfectly.
But then I try to recompile and I get completely different results.

So I wonder if this project has been built using a recent toolchain?

I am using a brand new install of xubuntu with the latest stable release of all tools.

**Comment by tonyg** [comment]
js-nacl is now using libsodium, compiled using emscripten's emsdk v1.36.
