### ISSUE TITLE
Problem with N greater than 2^14

### ISSUE THREAD

**Issue by anthonyc0603** [tonyg/js-scrypt#16]
This works

    var scrypt = scrypt_module_factory();
    var pwh=scrypt.crypto_scrypt(scrypt.encode_utf8("pleaseletmein"),
                scrypt.encode_utf8("SodiumChloride"),
                Math.pow(2,14), 8, 1, 224);

This fails

    var scrypt = scrypt_module_factory();
    var pwh=scrypt.crypto_scrypt(scrypt.encode_utf8("pleaseletmein"),
                scrypt.encode_utf8("SodiumChloride"),
                Math.pow(2,15), 8, 1, 224);

The difference is in the N parameter being 2^15 rather than 2^14

Any ideas?

Failure is as follows in the Firebug console

    uncaught exception: abort() at 
    wa@http://localhost/keybase/javascript/scrypt.js:10126:9      
    ua@http://localhost/keybase/javascript/scrypt.js:132:9 
    nc@http://localhost/keybase/javascript/scrypt.js:1266:9 
    bL@http://localhost/keybase/javascript/scrypt.js:4164:33    
    bu@http://localhost/keybase/javascript/scrypt.js:2168:33  
    crypto_scrypt@http://localhost/keybase/javascript/scrypt.js:10263:1  
    get_salt/<.success@http://localhost/keybase/javascript/main.js:91:1  
    jQuery.Callbacks/fire@http://code.jquery.com/jquery-latest.js:3119:1  
    jQuery.Callbacks/self.fireWith@http://code.jquery.com/jquery- 
    latest.js:3231:7 
    done@http://code.jquery.com/jquery-latest.js:9275:67 
    .send/callback@http://code.jquery.com/jquery-latest.js:9685:8   
    .send@http://code.jquery.com/jquery-latest.js:9691:7   
    .ajax@http://code.jquery.com/jquery-latest.js:9176:5  
    get_salt@http://localhost/keybase/javascript/main.js:95:9  
    @http://localhost/keybase/javascript/main.js:58:9  
    jQuery.event.dispatch@http://code.jquery.com/jquery-latest.js:4641:1  
    jQuery.event.add/elemData.handle@http://code.jquery.com/jquery-
    latest.js:4309:1

**Comment by 3nsoft** [comment]
My guess will be to try make scrypt_module_factory with bigger amount of memory. The N is linear to the necessary memory, therefore, if logN===14 works, and logN===15 fails, try to use double of default memory, i.e. logMem+=1.

**Comment by anthonyc0603** [comment]
var scrypt = scrypt_module_factory(67108864);

fixes the problem.  Many thanks for the suggestion.
