### ISSUE TITLE
add to `cdnjs`

### ISSUE THREAD

**Issue by maruilian11** [tonyg/js-scrypt#20]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding git tags for each version or put every version to npm so that we can use **git auto-update** or **npm auto-update** to add every released version to cdnjs.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/8253

**Comment by athanclark** [comment]
I've been trying to use rawgit.com as an alternative for this, but for some reason the .mem file isn't reachable :\

**Comment by maruilian11** [comment]
hi @athanclark, Is there any way to manually load `.mem from user specified source?

**Comment by maruilian11** [comment]
hi @athanclark, Is there any way to manually load the `.mem` file from user specified source?

**Comment by athanclark** [comment]
I don't believe there is; as referenced in [the docs' usage](https://www.google.com/trends/explore?date=all&q=third%20party%20candidate), they don't allow for a manual URL reference for the `.mem` file :\

**Comment by tonyg** [comment]
Hi - I've tagged v1.1.0 and the new v1.2.0; also, v1.2.0 no longer generates or requires the `.js.mem` file.

Does this help with getting it onto cdnjs?

**Comment by athanclark** [comment]
Hey sorry @tonyg this can be closed :)
