### ISSUE TITLE
Memory file not found in browser

### ISSUE THREAD

**Issue by max0d41** [tonyg/js-scrypt#21]
The file `scrypt_raw.js.mem` path can not be detected in my test environment, maybe also in production, I haven't tested it yet.

I tried to load the module with various ways but without success. After calling `scrypt_module_factory` the file `scrypt_raw.js.mem` will be loaded from document root where it does not exists. It should load it from the module directory found in my case under `/bowere_components/...`.

**Comment by tonyg** [comment]
I've just released v1.2.0 which no longer requires the .js.mem file at all. Hopefully this solves your issue.
