### ISSUE TITLE
Error: 'pre-main prep time: 4 ms'

### ISSUE THREAD

**Issue by adk1010** [tonyg/js-scrypt#23]
When running your implementation of scrypt I see a console.log message flagged as a warning that says 'pre-main prep time: 4 ms'.

Is this actually a warning that something has gone wrong, or have you given it that flag just so that the message stands out?

**Comment by tonyg** [comment]
It's a message automatically placed in the code by the emscripten compiler; I don't think it can be disabled (but if you discover otherwise, please let me know!). You should ignore it.

**Comment by adk1010** [comment]
You can easily just comment out that line in the code - that's what I've just done.

**Comment by tonyg** [comment]
True, though automating that reliably might be a bit tricky. If you feel strongly enough about it to have a go at automating the commenting-out, I'd be willing to take a patch.
