### ISSUE TITLE
decode_utf8 is throwing a URIError

### ISSUE THREAD

**Issue by athanclark** [tonyg/js-scrypt#26]
I'm trying to host all the js-scrypt assets statically on my own server, so I'm probably doing something that's hiding some resource that's needed, but I thought as per version >=1.2.0 no external assets were required. Do you have any idea what might be causing this? Specifically, it's a `malformed URI sequence` error.

**Comment by athanclark** [comment]
I've tried using js-nacl's implementations too, but stuffer from the same issue - it's raised from using `decodeURIComponent` in the definition of `decode_utf8()` - is `escape` not properly getting "rid" of the bad characters? I can see my hashes printing fine with `decode_latin1()` with outputs like `aÚiOó§/yÂ9lgádÒ
ÐDÝhKXOºö	²îV65£9`

**Comment by athanclark** [comment]
specifically this line: https://github.com/tonyg/js-nacl/blob/master/lib/nacl_factory.js#L69

**Comment by athanclark** [comment]
Replacing `escape()` with `encodeURIComponent()` stopped the error from being thrown. Is this isomorphism really necessary here? I would think `decodeURIComponent(encodeURIComponent(x)) == x` for all `x`.

MDN just says `escape()` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape).

**Comment by tonyg** [comment]
Can you paste a concrete example that triggers the problem please, so that I can reproduce it?

**Comment by athanclark** [comment]
Just try `decodeURIComponent(escape("aÚi���O�ó�§/�yÂ9l�gádÒ��� ÐDÝhK�XOºö �²�î�V65£9"))` in the browser console

**Comment by tonyg** [comment]
What I suspect is happening is that you're attempting to parse as UTF-8 a sequence of bytes that is not a valid UTF-8 byte sequence. For example,

```javascript
> s.decode_utf8(Uint8Array.from([0xe8, 0x82, 0xa1])); // valid UTF-8 byte seq
"股"
> s.decode_utf8(Uint8Array.from([0xe8, 0x28, 0xa1])); // invalid
URIError: malformed URI sequence
```

**Comment by athanclark** [comment]
Oh shoot okay, sorry about this!!

**Comment by tonyg** [comment]
No worries :-)
